// GENERATED by scripts/gen-photo-exif.mjs — do not edit by hand.
// Run `npm run exif` after adding or replacing photography.

export interface PhotoExif {
  iso?: number;
  exposureTime?: number;
  fNumber?: number;
  focalLength?: number;
  /** ISO 8601. */
  dateTaken?: string;
}

export const photoExif: Record<string, PhotoExif> = {
  "/images/photography/1.JPG": {"iso":800,"exposureTime":0.00625,"fNumber":4,"focalLength":22,"dateTaken":"2025-06-14T22:01:59.000Z"},
  "/images/photography/10.JPG": {"iso":640,"exposureTime":0.01,"fNumber":2.8,"focalLength":23,"dateTaken":"2025-11-06T21:10:16.000Z"},
  "/images/photography/11.JPG": {"iso":50,"exposureTime":30,"fNumber":1.8,"focalLength":23,"dateTaken":"2025-12-30T17:54:50.000Z"},
  "/images/photography/2.JPG": {"iso":1000,"exposureTime":0.00625,"fNumber":5.6,"focalLength":32,"dateTaken":"2025-06-14T21:57:35.000Z"},
  "/images/photography/3.JPG": {"iso":100,"exposureTime":0.008333333333333333,"fNumber":1.6,"focalLength":5,"dateTaken":"2025-12-03T08:35:35.000Z"},
  "/images/photography/4.JPG": {"iso":2500,"exposureTime":0.00625,"fNumber":5.6,"focalLength":42,"dateTaken":"2025-06-14T03:30:19.000Z"},
  "/images/photography/5.JPG": {"iso":2000,"exposureTime":0.01,"fNumber":5.6,"focalLength":50,"dateTaken":"2025-06-14T03:34:34.000Z"},
  "/images/photography/6.JPG": {"iso":160,"exposureTime":0.01,"fNumber":5.6,"focalLength":50,"dateTaken":"2025-06-14T22:28:20.000Z"},
  "/images/photography/7.JPG": {"iso":200,"exposureTime":0.004,"fNumber":5.6,"focalLength":105,"dateTaken":"2024-09-13T07:53:41.000Z"},
  "/images/photography/8.JPG": {"iso":80,"exposureTime":0.008333333333333333,"fNumber":1.6,"focalLength":5,"dateTaken":"2025-12-14T09:36:49.000Z"},
  "/images/photography/9.JPG": {"iso":200,"exposureTime":0.01,"fNumber":1.8,"focalLength":23,"dateTaken":"2025-11-06T20:59:04.000Z"},
};
