// GENERATED by scripts/gen-screenshot-dims.mjs — do not edit by hand.
// Run `npm run dims` after adding or replacing images.

export interface ImageDims {
  width: number;
  height: number;
}

export const screenshotDims: Record<string, ImageDims> = {
  "/images/community-building/ACCESS.jpg": { width: 2048, height: 1536 },
  "/images/community-building/ACCESSxDICE-151.jpg": { width: 2000, height: 1333 },
  "/images/digital-art/1.jpg": { width: 819, height: 1024 },
  "/images/digital-art/2.jpg": { width: 768, height: 1024 },
  "/images/digital-art/3.jpg": { width: 768, height: 1024 },
  "/images/event-photography/Devcon.jpg": { width: 2000, height: 1333 },
  "/images/event-photography/UXD.JPG": { width: 2000, height: 1124 },
  "/images/event-photography/UXPH.jpg": { width: 2048, height: 1280 },
  "/images/flag-football/595080906_1381678140636080_1318923575577891537_n.jpg": { width: 2000, height: 1333 },
  "/images/flag-football/595307726_25312621365065410_1546899642655596101_n.jpg": { width: 2048, height: 1365 },
  "/images/flag-football/597599121_1381677657302795_1083627458644293300_n.jpg": { width: 2000, height: 1333 },
  "/images/flag-football/597972817_1381680703969157_6090325612564495738_n.jpg": { width: 2000, height: 1333 },
  "/images/og/og.jpg": { width: 1200, height: 630 },
  "/images/pc/PC-2.jpg": { width: 2000, height: 2000 },
  "/images/pc/PC-3.jpg": { width: 2000, height: 2000 },
  "/images/pc/PC-4.jpg": { width: 2000, height: 2000 },
  "/images/pc/PC.jpg": { width: 2000, height: 2000 },
  "/images/photography/1.JPG": { width: 1333, height: 2000 },
  "/images/photography/10.JPG": { width: 1333, height: 2000 },
  "/images/photography/11.JPG": { width: 1333, height: 2000 },
  "/images/photography/2.JPG": { width: 1333, height: 2000 },
  "/images/photography/3.JPG": { width: 1125, height: 2000 },
  "/images/photography/4.JPG": { width: 1333, height: 2000 },
  "/images/photography/5.JPG": { width: 1333, height: 2000 },
  "/images/photography/6.JPG": { width: 1333, height: 2000 },
  "/images/photography/7.JPG": { width: 1122, height: 2000 },
  "/images/photography/8.JPG": { width: 1125, height: 2000 },
  "/images/photography/9.JPG": { width: 1333, height: 2000 },
  "/images/profile/763298974_1503461341795929_4209668349205839748_n.jpg": { width: 2000, height: 1332 },
  "/images/software-engineering/aula-course-platform/1.png": { width: 1440, height: 900 },
  "/images/software-engineering/aula-course-platform/2.png": { width: 1440, height: 900 },
  "/images/software-engineering/aula-course-platform/3.png": { width: 1440, height: 900 },
  "/images/software-engineering/aula-course-platform/4.png": { width: 1440, height: 900 },
  "/images/software-engineering/bevanda-inventory/1.png": { width: 1440, height: 900 },
  "/images/software-engineering/bevanda-inventory/2.png": { width: 1440, height: 988 },
  "/images/software-engineering/bevanda-inventory/3.png": { width: 1401, height: 1440 },
  "/images/software-engineering/bilibili-video-frontend/1.png": { width: 1440, height: 900 },
  "/images/software-engineering/bilibili-video-frontend/2.png": { width: 1440, height: 900 },
  "/images/software-engineering/bilibili-video-frontend/3.png": { width: 1440, height: 900 },
  "/images/software-engineering/health-key-pharma-scm/1.png": { width: 1440, height: 900 },
  "/images/software-engineering/health-key-pharma-scm/2.png": { width: 1440, height: 900 },
  "/images/software-engineering/health-key-pharma-scm/3.png": { width: 1440, height: 900 },
  "/images/software-engineering/health-key-pharma-scm/4.png": { width: 1440, height: 900 },
  "/images/software-engineering/health-key-pharma-scm/5.jpg": { width: 1440, height: 900 },
  "/images/software-engineering/health-key-pharma-scm/6.jpg": { width: 1440, height: 900 },
  "/images/software-engineering/immunization-management-system/1.png": { width: 1440, height: 757 },
  "/images/software-engineering/immunization-management-system/2.png": { width: 1440, height: 757 },
  "/images/software-engineering/immunization-management-system/3.png": { width: 1440, height: 757 },
  "/images/software-engineering/immunization-management-system/4.png": { width: 1440, height: 757 },
  "/images/software-engineering/immunizeme-v2/1.png": { width: 1440, height: 900 },
  "/images/software-engineering/immunizeme-v2/2.png": { width: 1440, height: 900 },
  "/images/software-engineering/immunizeme-v2/3.png": { width: 780, height: 1688 },
  "/images/software-engineering/immunizeme-v2/4.png": { width: 780, height: 1688 },
  "/images/software-engineering/mini-addu-sis/1.png": { width: 1280, height: 900 },
  "/images/software-engineering/mini-addu-sis/2.png": { width: 1280, height: 900 },
  "/images/software-engineering/mini-addu-sis/3.png": { width: 1280, height: 900 },
  "/images/software-engineering/mini-addu-sis/4.png": { width: 1280, height: 900 },
  "/images/software-engineering/pesopulse/1.png": { width: 780, height: 1688 },
  "/images/software-engineering/pesopulse/2.png": { width: 780, height: 1688 },
  "/images/software-engineering/pesopulse/3.png": { width: 780, height: 1688 },
  "/images/software-engineering/pesopulse/4.png": { width: 780, height: 1688 },
  "/images/software-engineering/tinas-aesthetics-wellness-booking/1.jpg": { width: 1920, height: 1080 },
  "/images/software-engineering/tinas-aesthetics-wellness-booking/2.jpg": { width: 1920, height: 1080 },
  "/images/software-engineering/tinas-aesthetics-wellness-booking/3.jpg": { width: 1920, height: 1080 },
  "/images/software-engineering/univents/1.png": { width: 400, height: 869 },
  "/images/software-engineering/univents/2.png": { width: 400, height: 869 },
  "/images/software-engineering/univents/3.png": { width: 400, height: 869 },
  "/images/software-engineering/univents/4.png": { width: 400, height: 869 },
};

/** Portrait enough to be a phone capture rather than a desktop one. */
export const PORTRAIT_RATIO = 1.2;

export function isPortrait(src: string): boolean {
  const d = screenshotDims[src];
  if (!d) return false;
  return d.height / d.width >= PORTRAIT_RATIO;
}
